spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true

server:
  port: 8083

ec:
  exchange: energy.exchange
  routing:
    produced: energy.produced
    used: energy.used
  queue:
    produced: meter.produced.q
    used: meter.used.q