spring:
  application:
    name: consumer-meter
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

server:
  port: 8083

ec:
  exchange: energy.exchange
  routing:
    produced: energy.produced
    used:     energy.used
  queue:
    produced: meter.produced.q
    used:     meter.used.q
