spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    flyway:
      enabled: true
      locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: ecuser
    password: ecpw


