server:
  port: 8082

spring:
  application:
    name: usage-worker

  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ec:
  exchange: energy.exchange
  queue:
    used: usage.used          # << echte Queue-Namen
    produced: usage.produced
  routing:
    used: energy.used         # << Routing-Keys auf dem Exchange
    produced: energy.produced
    update: energy.update     # << Veröffentlichung nach Aggregation
