server:
  port: 8082

spring:
  application:
    name: usage-worker
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    listener:
      simple:
        concurrency: 2         # optional für schnellere Abarbeitung
        max-concurrency: 6
        prefetch: 50

ec:
  exchange: energy.exchange
  routing:
    used:     energy.used
    produced: energy.produced
    update:   energy.update
  queue:
    used:     meter.used.q         # WICHTIG: gleich wie bei Sendern
    produced: meter.produced.q
